// Package routes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package routes

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Amount The amount to issue, transfer or redeem.
type Amount struct {
	// Code the code of the token
	Code string `json:"code"`

	// Value value in base units (usually cents)
	Value int64 `json:"value"`
}

// Counterparty The counterparty in a Transfer or Issuance transaction.
type Counterparty struct {
	Account string `json:"account"`

	// Node The node that holds the recipient account
	Node string `json:"node"`
}

// Error defines model for Error.
type Error struct {
	// Message High level error message
	Message string `json:"message"`

	// Payload Details about the error
	Payload string `json:"payload"`
}

// TransactionDetail transaction detail
type TransactionDetail struct {
	// Platform platform code
	Platform string `json:"platform"`

	// TransactionCategory transaction code
	TransactionCategory string `json:"transaction_category"`

	// TransactionType transaction type
	TransactionType string `json:"transaction_type"`
}

// TransferRequest Instructions to issue or transfer tokens to an account
type TransferRequest struct {
	// Amount The amount to issue, transfer or redeem.
	Amount Amount `json:"amount"`

	// Counterparty The counterparty in a Transfer or Issuance transaction.
	Counterparty Counterparty `json:"counterparty"`

	// Message optional message that will be sent and stored with the transfer transaction
	Message *string `json:"message,omitempty"`

	// TransactionDetail transaction detail
	TransactionDetail TransactionDetail `json:"transaction_detail"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = Error

// HealthSuccess defines model for HealthSuccess.
type HealthSuccess struct {
	// Message ok
	Message string `json:"message"`
}

// IssueSuccess defines model for IssueSuccess.
type IssueSuccess struct {
	Message string `json:"message"`

	// Payload Transaction id
	Payload string `json:"payload"`
}

// HarvestJSONRequestBody defines body for Harvest for application/json ContentType.
type HarvestJSONRequestBody = TransferRequest

// IssueJSONRequestBody defines body for Issue for application/json ContentType.
type IssueJSONRequestBody = TransferRequest

// KabayanJSONRequestBody defines body for Kabayan for application/json ContentType.
type KabayanJSONRequestBody = TransferRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Harvest the pond and collect tokens
	// (POST /harvest)
	Harvest(ctx echo.Context) error
	// Returns 200 if the service is healthy
	// (GET /healthz)
	Healthz(ctx echo.Context) error
	// Issue tokens of any kind to an account
	// (POST /issuer/issue)
	Issue(ctx echo.Context) error
	// Returns 200 if the service is ready to accept calls
	// (GET /readyz)
	Readyz(ctx echo.Context) error
	// Request token for kabayan
	// (POST /request-kabayan)
	Kabayan(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Harvest converts echo context to params.
func (w *ServerInterfaceWrapper) Harvest(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Harvest(ctx)
	return err
}

// Healthz converts echo context to params.
func (w *ServerInterfaceWrapper) Healthz(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Healthz(ctx)
	return err
}

// Issue converts echo context to params.
func (w *ServerInterfaceWrapper) Issue(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Issue(ctx)
	return err
}

// Readyz converts echo context to params.
func (w *ServerInterfaceWrapper) Readyz(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Readyz(ctx)
	return err
}

// Kabayan converts echo context to params.
func (w *ServerInterfaceWrapper) Kabayan(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Kabayan(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/harvest", wrapper.Harvest)
	router.GET(baseURL+"/healthz", wrapper.Healthz)
	router.POST(baseURL+"/issuer/issue", wrapper.Issue)
	router.GET(baseURL+"/readyz", wrapper.Readyz)
	router.POST(baseURL+"/request-kabayan", wrapper.Kabayan)

}

type ErrorResponseJSONResponse Error

type HealthSuccessJSONResponse struct {
	// Message ok
	Message string `json:"message"`
}

type IssueSuccessJSONResponse struct {
	Message string `json:"message"`

	// Payload Transaction id
	Payload string `json:"payload"`
}

type HarvestRequestObject struct {
	Body *HarvestJSONRequestBody
}

type HarvestResponseObject interface {
	VisitHarvestResponse(w http.ResponseWriter) error
}

type Harvest200JSONResponse struct{ IssueSuccessJSONResponse }

func (response Harvest200JSONResponse) VisitHarvestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type HarvestdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response HarvestdefaultJSONResponse) VisitHarvestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type HealthzRequestObject struct {
}

type HealthzResponseObject interface {
	VisitHealthzResponse(w http.ResponseWriter) error
}

type Healthz200JSONResponse struct{ HealthSuccessJSONResponse }

func (response Healthz200JSONResponse) VisitHealthzResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Healthz503JSONResponse struct{ ErrorResponseJSONResponse }

func (response Healthz503JSONResponse) VisitHealthzResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type IssueRequestObject struct {
	Body *IssueJSONRequestBody
}

type IssueResponseObject interface {
	VisitIssueResponse(w http.ResponseWriter) error
}

type Issue200JSONResponse struct{ IssueSuccessJSONResponse }

func (response Issue200JSONResponse) VisitIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type IssuedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response IssuedefaultJSONResponse) VisitIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ReadyzRequestObject struct {
}

type ReadyzResponseObject interface {
	VisitReadyzResponse(w http.ResponseWriter) error
}

type Readyz200JSONResponse struct{ HealthSuccessJSONResponse }

func (response Readyz200JSONResponse) VisitReadyzResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Readyz503JSONResponse struct{ ErrorResponseJSONResponse }

func (response Readyz503JSONResponse) VisitReadyzResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type KabayanRequestObject struct {
	Body *KabayanJSONRequestBody
}

type KabayanResponseObject interface {
	VisitKabayanResponse(w http.ResponseWriter) error
}

type Kabayan200JSONResponse struct{ IssueSuccessJSONResponse }

func (response Kabayan200JSONResponse) VisitKabayanResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type KabayandefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response KabayandefaultJSONResponse) VisitKabayanResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Harvest the pond and collect tokens
	// (POST /harvest)
	Harvest(ctx context.Context, request HarvestRequestObject) (HarvestResponseObject, error)
	// Returns 200 if the service is healthy
	// (GET /healthz)
	Healthz(ctx context.Context, request HealthzRequestObject) (HealthzResponseObject, error)
	// Issue tokens of any kind to an account
	// (POST /issuer/issue)
	Issue(ctx context.Context, request IssueRequestObject) (IssueResponseObject, error)
	// Returns 200 if the service is ready to accept calls
	// (GET /readyz)
	Readyz(ctx context.Context, request ReadyzRequestObject) (ReadyzResponseObject, error)
	// Request token for kabayan
	// (POST /request-kabayan)
	Kabayan(ctx context.Context, request KabayanRequestObject) (KabayanResponseObject, error)
}

type StrictHandlerFunc = runtime.StrictEchoHandlerFunc
type StrictMiddlewareFunc = runtime.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Harvest operation middleware
func (sh *strictHandler) Harvest(ctx echo.Context) error {
	var request HarvestRequestObject

	var body HarvestJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Harvest(ctx.Request().Context(), request.(HarvestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Harvest")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(HarvestResponseObject); ok {
		return validResponse.VisitHarvestResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// Healthz operation middleware
func (sh *strictHandler) Healthz(ctx echo.Context) error {
	var request HealthzRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Healthz(ctx.Request().Context(), request.(HealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Healthz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(HealthzResponseObject); ok {
		return validResponse.VisitHealthzResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// Issue operation middleware
func (sh *strictHandler) Issue(ctx echo.Context) error {
	var request IssueRequestObject

	var body IssueJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Issue(ctx.Request().Context(), request.(IssueRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Issue")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(IssueResponseObject); ok {
		return validResponse.VisitIssueResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// Readyz operation middleware
func (sh *strictHandler) Readyz(ctx echo.Context) error {
	var request ReadyzRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Readyz(ctx.Request().Context(), request.(ReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Readyz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ReadyzResponseObject); ok {
		return validResponse.VisitReadyzResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// Kabayan operation middleware
func (sh *strictHandler) Kabayan(ctx echo.Context) error {
	var request KabayanRequestObject

	var body KabayanJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Kabayan(ctx.Request().Context(), request.(KabayanRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Kabayan")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(KabayanResponseObject); ok {
		return validResponse.VisitKabayanResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZW28bNxb+KwfcfUgARiPH2QVWb842QIy8BI6LFo2NguIcaRhxyAnJkTs19N8LknPR",
	"XCTbaZDaQZ4siZxzvnP5Ph6ObwnXeaEVKmfJ4pYYtIVWFsOXN8Zoc1H/4n/gWjlUzn9kRSEFZ05olXyy",
	"WvnfLM8wZ/7Tvw2uyIL8K+msJ3HVJsEq2e12lKRouRGFN0IW0R00CMiOkrfIpMs+lJyjtQ8CgH+wvJAB",
	"dI7WsjWSBdEbb7QwukDjRIyxXb0doNEbQomrCv+gdUaoNfGQDX4uhcGULD62z163G/XyE3I3FVwdRC+8",
	"c2tL/JLoDoYwwEtJwSqpWToO79IwZRn330Ck9w61s/iQoLUBHBR3R+t4QghnuS5j4AOUGQILa+A0CJ8v",
	"Cs5DX6GBYDBFzGeE7lec69TjevPzxa+Eki2TJZLFyXw+Kn7c6J2uWCld90wfhcsQ/FbQK/Cfnd6gGqes",
	"dTWMIvwMQsGSWYRSCWfhWWlLJmUF3JPjOaFkpU3OPAah3H9fEUpyoURe5mQxb10J5XCNZlSeEEjjf1wZ",
	"Sv7vc4imYMZV02nmezs8VgaXe3n2rcoUx5j82DeDrDPOYxEJk4J7OCrWQd8oNCdj6rUPTPStaiszxOlX",
	"wGXMQaZlakNBDHJRCFQOGpt39bOKCWu2T6Us6tQhLYn9PKbFgjxAY96KdQYStyhhaO/+TP4JHRPSAlvq",
	"0oV0BFtfhdJ0XyeiozGAvZaANO7pNUYhmfPN7aFs+QtmXrDCo+se+50zh2ttKrIgZxdn7werTfN7+o+z",
	"25kfAmtWoKbHKKfTEI7Fdx9LcfGYlbDjrvpMgpvwRLsMHCzgCs0Ffi7RTmjsubLOlMGgbVXWc77V2aB3",
	"YY2pPYYN2NxK+LHDvxb6HSV8oEjHnuqp144eObTDByYbIkWhuBFSwhLBBoVQKVinDaZwI1wWBb2NtEvu",
	"XVVOWzYcQz6mz1i692KjTRonfU0fuUKt9ERV41npNXLvxPTBxyOzLuoMXjO+wRSWFTBIhY91WTpMQWK6",
	"RkOvVGHQotkKtYbCiC3jFZTWf/sNjYZ3St+ErfDeaL2yM7jMhIWz9+eQ4kooERp+ZbRyFl5BKlYrNL4O",
	"wSZHS+EmEzwDZDyDQrKIo951pYyW4egMusa1razDfAZX6kpdanCmAuFAl46CxKh+IXJTt7HVOcKqVGlo",
	"X63aM7y0aOwMfmGOxx5YMukPOHul1uigLFLmsxC6BbHrkprBmfA9VM26Q1K4SBDtMp/oyBLazShXqh0d",
	"ApYUrTO68pbD/OKE83JJLsMOf5ijsbGWJ7O57z5doGKFIAtyOpvPToNwuyyQL2FlKpw2Se3XJrci3YWh",
	"EY03RBYfhx1SP0IoKY0kC5I5VyySRGrOZKatW/xvPp8nrBDJ9iQhu+sdPeAm2UuM/fo+M2a2tXAVOv71",
	"uhNm43N/4L6tN0ReoXWvdVp9tevKUD8nxtxpBW27rieaHfWdKTFowd6N6+V8fghPuy/pXRsCmHp6vevB",
	"/n0ujOAHKxViOFaok16hKLFlnrNwgtf1CJwptIok4lpK5K4mgO93tvZ+G0fX/ySa0Gbhrvmnz+Iap7qs",
	"Xv+SivXvsTtK/jM//aJytVFdoCuNsvByPgcRFa0WVBAWYizVXpbbWCy59paSmNH45zC1Qqv9INYjIVbA",
	"1xwhegVMVbARKh3l4ltxqweoD8L3WLj4tWfFHSeDvzMGbi718giYl/tg6NAKZ0ZqG8ykTB0xczo6Zvpg",
	"kxyfFt44ZDxu2H0BC1Pos2Vp1PN9HR7EtT9bPLmiNHP30ynL5dSdrzfSThXpHsPmI6tMmFsjZ74zwjx0",
	"In+MhWl48z2SxuBaWPeoY/NgDbK0OjwNX8TlpzAMh0hCTTjHwgFnUtpjo3E97L7YsCWrmDo8Hb+rN/yY",
	"jx/HfFxnKtIQVtrApq3QtxqJD2M4HvYD34zQvweZPjItrasztqeAG2Ru6tZD65dz/v6ThReaEBQW2gsH",
	"JYrl2CVnKms9taj/rWRd/HmDVQymsejde3/h5WFnPridsL5GF3hoEQG3aKreK8T6pSaXyEyMZYNYWGDN",
	"y8XOQdMcYxcfauTxxl+/32WpUJ6iHcBO4nbXu78CAAD//7kHH8/0HwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
